[project]
name = "comfyui-easygoing-nodes"
description = "Experimental Text Encorder module and HDR Effects and color adjustment in LAB color space nodes by easygoing0114"
version = "1.1.0"
license = { file = "LICENSE.txt" }
dependencies  = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/easygoing0114/ComfyUI-easygoing-nodes"

[tool.comfy]
PublisherId = "easygoing0114"
DisplayName = "Easygoing Nodes"
Icon = ""
